config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  resources :blogs do
    resources :comments
    post :confirm, on: :collection
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post:confirm
    end
  end

  resources :poems, only: [:index, :show]

  root 'top#index'

  if Rails.env.development? #本番環境(heroku)では使わない。開発環境(ローカル)でのみ使う
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/poem.rb
class Poem < ActiveResource::Base
  self.site = "https://thawing-temple-85785.herokuapp.com"
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  def index
    @poems = Poem.all
  end

  def show
    @poem = Poem.find(params[:id])
  end


end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/poems/index.html.erb
<% @poems.each do |poem| %>
  <%= poem.title %>
  <%= poem.content %>
  <%= poem.auther %>
  <%= link_to "[詳細]", poem_path(poem.id) %>
  <br>
<% end %>

app/views/poems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @poem.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @poem.content %>
</p>

<p>
  <strong>Auther:</strong>
  <%= @poem.auther %>
</p>

<%= link_to "ポエム一覧に戻る", poems_path %>